@extends('layouts.admin')
@section('title','Người dùng · Royal Hotel')
@section('page-title','Quản lý người dùng')
@section('content')
<section class="module-head"><div><h1>Con người & quyền truy cập</h1><p>Quản lý khách hàng, lễ tân và quản trị viên trong một danh sách rõ ràng.</p></div><a class="primary-action" href="{{ route('admin.users.create') }}"><i class="bi bi-plus-lg"></i>Thêm tài khoản</a></section>
<form class="module-filter" method="GET" action="{{ route('admin.users.index') }}"><label class="search-field"><i class="bi bi-search"></i><input name="search" value="{{ request('search') }}" placeholder="Tìm tên, email hoặc tài khoản"></label><select name="role"><option value="">Mọi vai trò</option><option value="admin" @selected(request('role')==='admin')>Quản trị viên</option><option value="receptionist" @selected(request('role')==='receptionist')>Lễ tân</option><option value="customer" @selected(request('role')==='customer')>Khách hàng</option></select><select name="verified"><option value="">Mọi trạng thái</option><option value="1" @selected(request('verified')==='1')>Đang hoạt động</option><option value="0" @selected(request('verified')==='0')>Đã khóa</option></select><button><i class="bi bi-funnel"></i>Lọc</button><a href="{{ route('admin.users.index') }}" aria-label="Xóa bộ lọc"><i class="bi bi-arrow-counterclockwise"></i></a></form>
<section class="data-panel people-panel"><header><div><h2>Danh sách tài khoản</h2></div><span class="panel-note">{{ $users->total() }} tài khoản</span></header><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Tài khoản</th><th>Liên hệ</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>@forelse($users as $user)<tr><td>{{ $user->username }}</td><td>{{ $user->email }}<small>{{ $user->phone ?? 'Chưa có số điện thoại' }}</small></td><td><span class="soft-tag">{{ $user->role_label }}</span></td><td>@if($user->id===auth()->id())<span class="status-pill status-confirmed">Đang hoạt động</span>@elseif($user->verified)<button class="status-pill status-confirmed btn-toggle-status" data-id="{{ $user->id }}">Đang hoạt động</button>@else<button class="status-pill status-cancelled btn-toggle-status" data-id="{{ $user->id }}">Đã khóa</button>@endif</td><td><div class="row-actions"><a href="{{ route('admin.users.edit',$user) }}" title="Chỉnh sửa"><i class="bi bi-pencil"></i></a>@if($user->id!==auth()->id())<button class="btn-delete" data-id="{{ $user->id }}" data-name="{{ $user->fullname }}" title="Xóa"><i class="bi bi-trash3"></i></button><form id="delete-form-{{ $user->id }}" action="{{ route('admin.users.destroy',$user) }}" method="POST" hidden>@csrf @method('DELETE')</form>@endif</div></td></tr>@empty<tr><td colspan="5" class="empty-state">Không tìm thấy tài khoản phù hợp.</td></tr>@endforelse</tbody></table></div>@if($users->hasPages())<footer class="panel-footer">{{ $users->links('pagination.royal') }}</footer>@endif</section>
<div class="modal fade" id="deleteModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-body p-4"><span class="danger-icon"><i class="bi bi-trash3"></i></span><h5 class="mt-3">Xóa tài khoản?</h5><p class="text-muted">Tài khoản <strong id="delete-name"></strong> sẽ bị xóa vĩnh viễn.</p><div class="d-flex justify-content-end gap-2"><button class="btn btn-light" data-bs-dismiss="modal">Giữ lại</button><button class="btn btn-danger" id="confirm-delete">Xóa</button></div></div></div></div></div>
<div class="toast-container position-fixed bottom-0 end-0 p-3"><div id="statusToast" class="toast border-0"><div class="d-flex"><div class="toast-body" id="toastMessage"></div><button class="btn-close me-2 m-auto" data-bs-dismiss="toast"></button></div></div></div>
@endsection
@push('scripts')
<script>
let deleteTargetId=null;const deleteModal=new bootstrap.Modal(document.getElementById('deleteModal'));document.querySelectorAll('.btn-delete').forEach(btn=>btn.addEventListener('click',()=>{deleteTargetId=btn.dataset.id;document.getElementById('delete-name').textContent=btn.dataset.name;deleteModal.show()}));document.getElementById('confirm-delete').addEventListener('click',()=>deleteTargetId&&document.getElementById('delete-form-'+deleteTargetId).submit());
const toast=new bootstrap.Toast(document.getElementById('statusToast'));document.querySelectorAll('.btn-toggle-status').forEach(btn=>btn.addEventListener('click',async function(){if(this.disabled)return;this.disabled=true;try{const res=await fetch('/admin/users/'+this.dataset.id+'/toggle-verified',{method:'PATCH',headers:{'X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json'}});const json=await res.json();if(!res.ok||!json.success)throw new Error(json.message||'Không thể cập nhật');this.className='status-pill '+(json.verified?'status-confirmed':'status-cancelled')+' btn-toggle-status';this.textContent=json.verified?'Đang hoạt động':'Đã khóa';document.getElementById('toastMessage').textContent=json.message;toast.show()}catch(error){document.getElementById('toastMessage').textContent=error.message;toast.show()}finally{this.disabled=false}}));
</script>
@endpush
